#!/sbin/sh
# exit codes
E_AVM=10;		# Aslib Version Mismatch
E_OSC=11;		# OS check ERROR
E_SDM=12;		# SDK mismatch
E_NME=13;		# Not enough space for zipfile extraction
E_ZEF=14;		# Zipfile Extraction Failed
E_FRS=15;       # Failed to remove SOURCEDIR
E_UMS=16;		# Unable to mount system
E_UAS=17;		# Unable to determine SDK
E_AAE=18;		# asAddon restriction flashmode only
E_ZVU=19;		# asExtract ZIP variable undefined or does not exist
E_INE=20;		# asInstall ERROR
E_NDM=21;		# no user mountpoints
E_SVZ=22;		# zipfile to big for system
E_ANL=23;		# aslib is not loadable, check aslib script
# END OF FILE
